apiVersion: v1
kind: Service
metadata:
  name: microservice-app-api
  labels:
    app: microservice-app-api
spec:
  type: NodePort
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: microservice-app-api
