apiVersion: v1
kind: Service
metadata:
  name: microservice-app-name-service
  labels:
    app: microservice-app-name-service
spec:
  type: ClusterIP
  ports:
    - port: 7070
      protocol: TCP
  selector:
    app: microservice-app-name-service
