apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-app-api
  labels:
    app: microservice-app-api
spec:
  selector:
    matchLabels:
      app: microservice-app-api
  template:
    metadata:
      labels:
        app: microservice-app-api
    spec:
      containers:
        - name: microservice-app-api
          image: "microservice-app-api:latest"
          env:
            - name: NAME_HOST
              value: 'microservice-app-name-service.default.svc.cluster.local'
            - name: NAME_PORT
              value: '7070'
          imagePullPolicy: IfNotPresent
